export const DECADES = {
  "1970s": {
    decade: "1970s",
    years: "1970–1979",
    tagline: "The decade that invented everything.",
    theme: {
      bg: "#1a0e00",
      bgCard: "#241400",
      accent: "#E8871A",
      accentDim: "rgba(232,135,26,0.12)",
      accentBorder: "rgba(232,135,26,0.25)",
      text: "#F5E6C8",
      textMuted: "#A08050",
      gradient: "linear-gradient(135deg, #1a0e00 0%, #2d1800 50%, #1a0e00 100%)",
      heroGradient: "linear-gradient(180deg, #3d2200 0%, #1a0e00 100%)",
      pill: "#3d2200",
      font: "'Playfair Display', Georgia, serif",
    },
    era: {
      headline: "Welcome to the 1970s",
      subline: "Funk is in the air. Vinyl crackles. The disco ball spins.",
      description: "Funk, soul, disco, classic rock, reggae, and punk all collide. Vinyl rules, FM radio drives discovery, and hip-hop is quietly being born in the Bronx.",
    },
    genres: ["Funk & Soul", "Classic Rock", "Disco", "Folk", "Progressive Rock", "Soft Rock", "Reggae", "Early Punk"],
    culturalMoments: [
      {
        title: "The vinyl era at its peak",
        body: "No streaming, no skipping. You bought an album, you listened front to back, you read the liner notes. Music was a physical object you owned and kept forever.",
      },
      {
        title: "FM radio changed everything",
        body: "Album-oriented rock stations played full songs, full albums. Radio wasn't just hits — it was discovery. The DJ was a tastemaker, not an algorithm.",
      },
      {
        title: "Disco backlash and the birth of punk",
        body: "By 1977 the culture was splitting in two — glitter and cocaine at Studio 54, or three chords and rage in a London basement. Both mattered. Both won.",
      },
      {
        title: "Hip-hop is born in the Bronx",
        body: "1973. A DJ named Kool Herc throws a party on Sedgwick Avenue. By 1979 Sugarhill Gang puts it on record. The world doesn't know yet what just happened.",
      },
    ],
    definingAlbum: {
      title: "What's Going On",
      artist: "Marvin Gaye",
      year: 1971,
      why: "The album that proved pop music could be about something. Vietnam, poverty, the environment — Gaye turned Motown into protest art. Nothing sounded like this before it. Everything after it tried to.",
    },
    songs: [
      { rank: 1, title: "Stayin' Alive", artist: "Bee Gees", year: 1977, genre: "Disco", mood: ["dancefloor classic", "Saturday night"], tier: "hit", why: "The song that made the disco era immortal. That bassline never gets old." },
      { rank: 2, title: "Hotel California", artist: "Eagles", year: 1977, genre: "Classic Rock", mood: ["late night drive", "cinematic"], tier: "hit", why: "Six minutes of guitar myth-making. The most analysed song of the decade." },
      { rank: 3, title: "Bohemian Rhapsody", artist: "Queen", year: 1975, genre: "Rock", mood: ["epic", "theatrical"], tier: "hit", why: "Opera, hard rock, and a cappella in one song. Radio refused to play it. It was #1 for nine weeks." },
      { rank: 4, title: "Le Freak", artist: "Chic", year: 1978, genre: "Disco/Funk", mood: ["dancefloor classic", "pure joy"], tier: "hit", why: "Born from being turned away at Studio 54. Nile Rodgers wrote it in fury. It became the best-selling single in Atlantic Records history." },
      { rank: 5, title: "Born to Run", artist: "Bruce Springsteen", year: 1975, genre: "Rock", mood: ["escape", "working class anthem"], tier: "hit", why: "Springsteen on the cover of Time and Newsweek the same week. The great American road song." },
      { rank: 6, title: "Superstition", artist: "Stevie Wonder", year: 1972, genre: "Funk/Soul", mood: ["irresistible groove", "urgent"], tier: "hit", why: "Written for Jeff Beck. Stevie kept it. The opening clavinet riff is one of the most recognisable in history." },
      { rank: 7, title: "Go Your Own Way", artist: "Fleetwood Mac", year: 1977, genre: "Soft Rock", mood: ["breakup anthem", "bitter"], tier: "hit", why: "Lindsey Buckingham wrote it about Stevie Nicks. She hated it. She sang on it anyway." },
      { rank: 8, title: "Roxanne", artist: "The Police", year: 1978, genre: "Punk/Rock", mood: ["tension", "obsession"], tier: "hit", why: "A punk band plays a tango. About a sex worker in Paris. Radio initially banned it. Then played it forever." },
      { rank: 9, title: "No Woman No Cry", artist: "Bob Marley", year: 1974, genre: "Reggae", mood: ["comfort", "warmth"], tier: "hit", why: "Live at the Lyceum, London. Marley stretches it to seven minutes. Nobody wants it to end." },
      { rank: 10, title: "Dream On", artist: "Aerosmith", year: 1973, genre: "Rock", mood: ["ambition", "yearning"], tier: "hit", why: "Steven Tyler wrote it at 17. It took three years to chart. Then it never stopped." },
      { rank: 11, title: "What's Going On", artist: "Marvin Gaye", year: 1971, genre: "Soul", mood: ["protest", "tender"], tier: "defining", why: "Motown told him not to release it. He threatened to quit. It became the greatest album of the era." },
      { rank: 12, title: "Papa Was a Rollin' Stone", artist: "The Temptations", year: 1972, genre: "Soul", mood: ["epic", "storytelling"], tier: "defining", why: "Twelve minutes of orchestral soul. Three sons, one funeral, one question. Norman Whitfield produced something that felt like a film." },
      { rank: 13, title: "I Will Survive", artist: "Gloria Gaynor", year: 1978, genre: "Disco", mood: ["empowerment", "comeback"], tier: "defining", why: "Originally the B-side. DJs flipped it. The rest is feminist anthem history." },
      { rank: 14, title: "Rapper's Delight", artist: "Sugarhill Gang", year: 1979, genre: "Hip-Hop", mood: ["historic", "joyful"], tier: "defining", why: "The first rap song most people ever heard. Fifteen minutes long. Samples Chic. Changes music forever." },
      { rank: 15, title: "Tangled Up in Blue", artist: "Bob Dylan", year: 1975, genre: "Folk", mood: ["poetic", "road trip"], tier: "defining", why: "Dylan rewrote it ten times over five years. Seven characters, one narrator, no clean timeline. Still perfect." },
      { rank: 16, title: "Wish You Were Here", artist: "Pink Floyd", year: 1975, genre: "Prog Rock", mood: ["melancholy", "longing"], tier: "defining", why: "Written for Syd Barrett, who showed up unannounced to the recording session. Nobody recognised him." },
      { rank: 17, title: "Anarchy in the U.K.", artist: "Sex Pistols", year: 1976, genre: "Punk", mood: ["rage", "revolution"], tier: "defining", why: "Two minutes and the music press declared rock dead and reborn simultaneously." },
      { rank: 18, title: "Heart of Gold", artist: "Neil Young", year: 1972, genre: "Folk", mood: ["searching", "introspective"], tier: "defining", why: "The only #1 of Young's career. He hated that it made him famous and spent the rest of the decade running from it." },
      { rank: 19, title: "Love to Love You Baby", artist: "Donna Summer", year: 1975, genre: "Disco", mood: ["sensual", "late night"], tier: "defining", why: "Seventeen minutes in its full form. Giorgio Moroder turns a studio in Munich into the most seductive room on earth." },
      { rank: 20, title: "Don't Stop 'Til You Get Enough", artist: "Michael Jackson", year: 1979, genre: "Funk/Pop", mood: ["euphoric", "transitional"], tier: "defining", why: "The moment Michael Jackson stopped being a Jackson 5 member and became Michael Jackson." },
      { rank: 21, title: "Inner City Blues", artist: "Marvin Gaye", year: 1971, genre: "Soul", mood: ["protest", "urban"], tier: "deepcut", why: "The closing track of What's Going On. Taxes, unemployment, Vietnam — Gaye puts the whole city's pain to music." },
      { rank: 22, title: "Right Place Wrong Time", artist: "Dr. John", year: 1973, genre: "Funk/R&B", mood: ["swampy", "irresistible"], tier: "deepcut", why: "New Orleans funk at its absolute peak. Allen Toussaint production. The groove never once loosens its grip." },
      { rank: 23, title: "Across 110th Street", artist: "Bobby Womack", year: 1972, genre: "Soul", mood: ["gritty", "cinematic"], tier: "deepcut", why: "The Harlem of 1972 in four minutes. Quentin Tarantino brought it back in Jackie Brown. A new generation discovered it." },
      { rank: 24, title: "Can't You Hear Me Knocking", artist: "Rolling Stones", year: 1971, genre: "Rock", mood: ["raw", "extended groove"], tier: "deepcut", why: "Hard rock for three minutes, then seven minutes of jazz improvisation the band didn't plan. They kept it." },
      { rank: 25, title: "West End Blues", artist: "Gil Scott-Heron", year: 1971, genre: "Soul/Spoken Word", mood: ["political", "urgent"], tier: "deepcut", why: "The godfather of rap, before rap existed. Poetry over piano. The blueprint for every socially conscious artist that followed." },
      { rank: 26, title: "Once in a Lifetime", artist: "Talking Heads", year: 1980, genre: "New Wave", mood: ["existential", "danceable"], tier: "deepcut", why: "Technically 1980 but impossible to separate from the late 70s art-punk scene that made Talking Heads possible." },
      { rank: 27, title: "Harvest", artist: "Neil Young", year: 1972, genre: "Folk", mood: ["quiet", "rural"], tier: "deepcut", why: "Recorded partly in a barn. Linda Ronstadt and James Taylor on harmonies. The sound of American simplicity." },
      { rank: 28, title: "Boogie Wonderland", artist: "Earth, Wind & Fire", year: 1979, genre: "Funk/Disco", mood: ["euphoric", "layered"], tier: "deepcut", why: "A 9-piece band, a 6-piece brass section, and strings. Maurice White orchestrates the last great disco moment." },
      { rank: 29, title: "For the Love of Money", artist: "The O'Jays", year: 1973, genre: "Soul/Funk", mood: ["gritty", "cautionary"], tier: "deepcut", why: "That bass riff. Gamble & Huff Philadelphia soul at its darkest. The Apprentice theme ruined it for a generation. Listen past that." },
      { rank: 30, title: "Redemption Song", artist: "Bob Marley", year: 1979, genre: "Reggae/Folk", mood: ["profound", "acoustic"], tier: "deepcut", why: "Marley's last recorded before his diagnosis. Just a guitar, a voice, and words that feel like they were always true." },
    ],
    bridges: [
      { then: "Bee Gees", now: "Dua Lipa", why: "Disco DNA, floor-filling confidence, pop precision" },
      { then: "Fleetwood Mac", now: "Boygenius", why: "Band tension turned into extraordinary art" },
      { then: "Marvin Gaye", now: "Frank Ocean", why: "Soul with social conscience, complete artistic control" },
      { then: "Bob Dylan", now: "Phoebe Bridgers", why: "Poetic folk, emotionally devastating, never obvious" },
      { then: "Donna Summer", now: "The Weeknd", why: "Late night, cinematic, Giorgio Moroder → Max Martin lineage" },
      { then: "Sex Pistols", now: "Wet Leg", why: "Punk spirit, sharp wit, refuses to take itself too seriously" },
      { then: "Bob Marley", now: "Koffee", why: "Reggae lineage, conscious lyrics, acoustic at heart" },
      { then: "Stevie Wonder", now: "Bruno Mars", why: "Funk-rooted, irresistibly groovy, technically flawless" },
      { then: "Sugarhill Gang", now: "Kendrick Lamar", why: "Hip-hop from party to poetry, the line runs direct" },
      { then: "Earth Wind & Fire", now: "Anderson .Paak", why: "Orchestral funk, joy as a political statement" },
    ],
  },

  "1980s": {
    decade: "1980s",
    years: "1980–1989",
    tagline: "Neon, synths, and the birth of the music video.",
    theme: {
      bg: "#0d0020",
      bgCard: "#130030",
      accent: "#C724E8",
      accentDim: "rgba(199,36,232,0.12)",
      accentBorder: "rgba(199,36,232,0.3)",
      text: "#F0D0FF",
      textMuted: "#8050A0",
      gradient: "linear-gradient(135deg, #0d0020 0%, #1a0040 50%, #0d0020 100%)",
      heroGradient: "linear-gradient(180deg, #2a0060 0%, #0d0020 100%)",
      pill: "#1a0040",
      font: "'Syncopate', 'Arial Narrow', sans-serif",
    },
    era: {
      headline: "Welcome to the 1980s",
      subline: "MTV just launched. Synths are everywhere. Your jacket has shoulder pads.",
      description: "The music video rewrites the rules. Synthesizers replace session musicians. Madonna and Michael Jackson become the first true global pop icons.",
    },
    genres: ["Synth-pop", "New Wave", "Hair Metal", "Hip-Hop", "R&B/Funk", "Post-Punk", "Pop", "Electronic"],
    culturalMoments: [
      {
        title: "MTV launches — August 1, 1981",
        body: "The first video: \"Video Killed the Radio Star.\" Within two years, if you weren't visual you weren't relevant. Michael Jackson understood this before anyone else.",
      },
      {
        title: "The Walkman made music personal",
        body: "For the first time you could take your soundtrack everywhere. Music became private, intimate, yours alone on the subway. The world outside disappeared.",
      },
      {
        title: "The CD arrives in 1982",
        body: "\"Perfect sound forever\" they said. The album artwork shrank, the skip button appeared, and listening habits quietly started to change forever.",
      },
      {
        title: "Hip-hop moves from the street to the studio",
        body: "Run-DMC wear Adidas on stage without laces. Grandmaster Flash puts the Bronx on record. By 1988 NWA is making music that terrifies politicians.",
      },
    ],
    definingAlbum: {
      title: "Purple Rain",
      artist: "Prince",
      year: 1984,
      why: "He played every instrument, wrote every song, directed the film. Rock, R&B, funk, pop — none of those labels fit. It sold 25 million copies and still sounds like nothing else.",
    },
    songs: [
      { rank: 1, title: "Billie Jean", artist: "Michael Jackson", year: 1982, genre: "Pop/R&B", mood: ["iconic", "paranoid"], tier: "hit", why: "The bassline. The glove. The moonwalk on Motown 25. The greatest pop moment ever televised." },
      { rank: 2, title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987, genre: "Hard Rock", mood: ["nostalgic", "explosive"], tier: "hit", why: "Slash wrote the riff as a joke. Axl heard it, wrote lyrics about his girlfriend in ten minutes. Somehow perfect." },
      { rank: 3, title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: 1983, genre: "Pop", mood: ["carefree", "defiant"], tier: "hit", why: "Written by a man. Cyndi Lauper rewrote it entirely, turned it into a feminist anthem. The video cost $25,000 and changed everything." },
      { rank: 4, title: "Like a Prayer", artist: "Madonna", year: 1989, genre: "Pop", mood: ["provocative", "gospel energy"], tier: "hit", why: "Pepsi paid $5m for the rights. Then saw the video with burning crosses and pulled it. The controversy made it #1 everywhere." },
      { rank: 5, title: "Don't You (Forget About Me)", artist: "Simple Minds", year: 1985, genre: "New Wave", mood: ["teenage longing", "bittersweet"], tier: "hit", why: "Simple Minds almost turned it down. John Hughes insisted. The Breakfast Club ending made it eternal." },
      { rank: 6, title: "Take On Me", artist: "a-ha", year: 1985, genre: "Synth-pop", mood: ["romantic", "euphoric"], tier: "hit", why: "Failed twice, re-released with that pencil-sketch video. The animation took 16 weeks to produce. Then it was everywhere." },
      { rank: 7, title: "Every Breath You Take", artist: "The Police", year: 1983, genre: "Pop/Rock", mood: ["obsession", "dark romance"], tier: "hit", why: "Sting wrote it at Goldeneye, Ian Fleming's Jamaica house. He says it's about surveillance and control. People play it at weddings." },
      { rank: 8, title: "Purple Rain", artist: "Prince", year: 1984, genre: "R&B/Rock", mood: ["transcendent", "emotional peak"], tier: "hit", why: "Recorded live in one take at First Avenue, Minneapolis. The crowd didn't know they were making history." },
      { rank: 9, title: "Jump", artist: "Van Halen", year: 1984, genre: "Arena Rock", mood: ["pure energy", "stadium-sized"], tier: "hit", why: "Eddie Van Halen had the synth riff for years. The rest of the band hated it. It became their only #1 single." },
      { rank: 10, title: "I Wanna Dance With Somebody", artist: "Whitney Houston", year: 1987, genre: "Pop/R&B", mood: ["pure joy", "peak Whitney"], tier: "hit", why: "Four octaves in four minutes. Narada Michael Walden production. The most joyful pop song of the decade." },
      { rank: 11, title: "Blue Monday", artist: "New Order", year: 1983, genre: "Electronic/New Wave", mood: ["melancholy dancefloor", "cold euphoria"], tier: "defining", why: "The best-selling 12-inch single of all time. Cost more to manufacture than they earned per copy for years. Joy Division becomes the future." },
      { rank: 12, title: "Planet Rock", artist: "Afrika Bambaataa", year: 1982, genre: "Electronic/Hip-Hop", mood: ["futuristic", "genre-founding"], tier: "defining", why: "Samples Kraftwerk. Adds a drum machine. Invents electro. Every electronic genre since has this in its DNA." },
      { rank: 13, title: "When Doves Cry", artist: "Prince", year: 1984, genre: "Funk/Pop", mood: ["vulnerable", "singular"], tier: "defining", why: "No bass line. Prince removed it at the last minute. The absence creates the most unusual #1 record ever made." },
      { rank: 14, title: "The Message", artist: "Grandmaster Flash & the Furious Five", year: 1982, genre: "Hip-Hop", mood: ["urgent", "social commentary"], tier: "defining", why: "\"Don't push me 'cause I'm close to the edge.\" The South Bronx in seven minutes. Hip-hop discovers it can document reality." },
      { rank: 15, title: "Personal Jesus", artist: "Depeche Mode", year: 1989, genre: "Electronic/Rock", mood: ["dark", "seductive"], tier: "defining", why: "A guitar riff, a drum machine, and a lyric about Priscilla Presley. Johnny Cash covered it twenty years later. Both versions essential." },
      { rank: 16, title: "Sign 'O' the Times", artist: "Prince", year: 1987, genre: "Pop/R&B", mood: ["socially aware", "stunning range"], tier: "defining", why: "AIDS, gang violence, a tornado in Kansas, a baby with no name — Prince surveys the world in three minutes and thirty seconds." },
      { rank: 17, title: "Bizarre Love Triangle", artist: "New Order", year: 1986, genre: "Synth-pop", mood: ["euphoric sadness", "dancefloor"], tier: "defining", why: "Bernard Sumner can't sing. The vulnerability makes it. Factory Records, Manchester, the Haçienda — all of it in one song." },
      { rank: 18, title: "Rock Box", artist: "Run-DMC", year: 1984, genre: "Hip-Hop/Rock", mood: ["genre collision", "historic"], tier: "defining", why: "The first rap video on MTV. Hard rock guitars over a hip-hop beat. The walls between genres start coming down." },
      { rank: 19, title: "Once in a Lifetime", artist: "Talking Heads", year: 1980, genre: "New Wave", mood: ["existential", "danceable"], tier: "defining", why: "David Byrne in an oversized suit, asking how he got here. Afrobeat rhythms, Brian Eno production, suburban dread as art." },
      { rank: 20, title: "Running Up That Hill", artist: "Kate Bush", year: 1985, genre: "Art Pop", mood: ["ethereal", "emotionally massive"], tier: "defining", why: "\"A Deal With God\" was the original title. BBC made her change it. Stranger Things brought it back. It was always this big." },
      { rank: 21, title: "This Charming Man", artist: "The Smiths", year: 1983, genre: "Post-Punk", mood: ["witty melancholy", "jangly"], tier: "deepcut", why: "Johnny Marr's guitar in one take. Morrissey's lyric about a punctured bicycle and a pompous man. Indie music finds its voice." },
      { rank: 22, title: "Love Will Tear Us Apart", artist: "Joy Division", year: 1980, genre: "Post-Punk", mood: ["beautiful despair", "timeless"], tier: "deepcut", why: "Ian Curtis died before it was released. Bernard Sumner and Peter Hook pressed it anyway. It charted after his death." },
      { rank: 23, title: "West End Girls", artist: "Pet Shop Boys", year: 1984, genre: "Synth-pop", mood: ["urban", "literary"], tier: "deepcut", why: "Neil Tennant wrote the lyrics on a train. T.S. Eliot meets the Northern Line. Georgio Moroder produces it in LA. Somehow British." },
      { rank: 24, title: "Vienna", artist: "Ultravox", year: 1980, genre: "Synth-pop", mood: ["cinematic", "overlooked classic"], tier: "deepcut", why: "Kept off #1 by Joe Dolce's \"Shaddap You Face.\" Midge Ure's masterpiece. The most beautiful song that almost nobody talks about." },
      { rank: 25, title: "Situation", artist: "Yazoo", year: 1982, genre: "Synth-pop", mood: ["urgent", "underrated"], tier: "deepcut", why: "Vince Clarke left Depeche Mode, found Alison Moyet, made something completely different and completely essential." },
      { rank: 26, title: "I Melt With You", artist: "Modern English", year: 1982, genre: "New Wave", mood: ["romantic", "timeless"], tier: "deepcut", why: "Written about nuclear apocalypse. Sounds like the best weekend of your life. That tension is why it still works." },
      { rank: 27, title: "Fade to Black", artist: "Metallica", year: 1984, genre: "Metal", mood: ["dark", "emotionally raw"], tier: "deepcut", why: "Metal's first ballad. Acoustic intro, then the riff. Their equipment had been stolen. The song is about giving up. It helped people not to." },
      { rank: 28, title: "Genius of Love", artist: "Tom Tom Club", year: 1981, genre: "Funk/New Wave", mood: ["playful", "groove-driven"], tier: "deepcut", why: "Tina Weymouth from Talking Heads, bored on tour. Samples James Brown, Kurtis Blow, Hamilton Bohannon. Hip-hop's most sampled record." },
      { rank: 29, title: "Controversy", artist: "Prince", year: 1981, genre: "Funk", mood: ["provocative", "restless"], tier: "deepcut", why: "\"Am I black or white? Am I straight or gay?\" Prince asks questions the decade isn't ready for. He asks them anyway." },
      { rank: 30, title: "Golden Years", artist: "David Bowie", year: 1975, genre: "Soul/Pop", mood: ["warm", "transitional"], tier: "deepcut", why: "Bowie in his plastic soul phase, written for Elvis who turned it down. The most accessible song Bowie ever made." },
    ],
    bridges: [
      { then: "Michael Jackson", now: "The Weeknd", why: "Precision pop, visual spectacle, complete artistic control" },
      { then: "Madonna", now: "Charli XCX", why: "Provocateur pop, always culturally ahead, never apologetic" },
      { then: "New Order", now: "Disclosure", why: "Dancefloor melancholy, electronic soul, the club as emotional space" },
      { then: "The Smiths", now: "The 1975", why: "Literate indie, emotionally dramatic, lead singer as theatrical force" },
      { then: "Prince", now: "Frank Ocean", why: "Genre-less genius, complete artistic control, vulnerability as strength" },
      { then: "Cyndi Lauper", now: "Olivia Rodrigo", why: "Female pop with actual bite, the fun is never the whole story" },
      { then: "Depeche Mode", now: "Lorde", why: "Dark synth pop, outsider sensibility, refuses mainstream compromise" },
      { then: "Whitney Houston", now: "Beyoncé", why: "Vocal power, cultural icon, raises the bar every decade" },
      { then: "Grandmaster Flash", now: "Kendrick Lamar", why: "Hip-hop as journalism, the street as subject, truth as the only option" },
      { then: "Kate Bush", now: "Lana Del Rey", why: "Art pop, cinematic ambition, sui generis and proud of it" },
    ],
  },

  "1990s": {
    decade: "1990s",
    years: "1990–1999",
    tagline: "The last decade before the internet changed everything.",
    theme: {
      bg: "#0a0015",
      bgCard: "#120020",
      accent: "#00D4B4",
      accentDim: "rgba(0,212,180,0.1)",
      accentBorder: "rgba(0,212,180,0.25)",
      text: "#E0F5F0",
      textMuted: "#508070",
      gradient: "linear-gradient(135deg, #0a0015 0%, #001520 50%, #0a0015 100%)",
      heroGradient: "linear-gradient(180deg, #002030 0%, #0a0015 100%)",
      pill: "#001520",
      font: "'Courier New', monospace",
    },
    era: {
      headline: "Welcome to the 1990s",
      subline: "Grunge kills hair metal overnight. TLC rules R&B. Napster is coming.",
      description: "The CD store is a cultural institution. TRL makes pop stars in real time. Hip-hop becomes the dominant American art form. And nobody knows the internet is about to end all of it.",
    },
    genres: ["Grunge / Alt Rock", "Golden Age Hip-Hop", "R&B / Neo-Soul", "Britpop", "Pop (TRL era)", "Trip-Hop", "Electronic", "Latin Pop"],
    culturalMoments: [
      {
        title: "The CD store was a cultural institution",
        body: "Tower Records, HMV, Virgin Megastore. You went in for one album and left with three. The cover art, the liner notes, the clerk's recommendation — all of it mattered. You couldn't sample before buying.",
      },
      {
        title: "TRL made pop stars in real time",
        body: "MTV's Total Request Live was appointment television. Carson Daly counted down videos voted for by actual teenagers calling an actual phone number. Chaos, screaming, history.",
      },
      {
        title: "Napster arrives in 1999 and breaks everything",
        body: "Suddenly 15 million songs are free. The industry panics. The teenagers don't care. The 90s end and the music business is never the same again.",
      },
      {
        title: "Hip-hop becomes the dominant American art form",
        body: "By 1998 rap outsells country. Biggie and Tupac are gone. Jay-Z, Eminem, Lauryn Hill and Missy Elliott pick up the decade's crown and don't drop it.",
      },
    ],
    definingAlbum: {
      title: "The Miseducation of Lauryn Hill",
      artist: "Lauryn Hill",
      year: 1998,
      why: "Ten Grammys. Written, produced, and performed almost entirely alone. Hip-hop, soul, reggae, gospel — all of it, seamlessly. She was 23.",
    },
    songs: [
      { rank: 1, title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991, genre: "Grunge", mood: ["generational explosion", "raw"], tier: "hit", why: "Kurt Cobain called it a rip-off of a Pixies song. It killed hair metal overnight and made a reluctant icon of a man who never wanted to be one." },
      { rank: 2, title: "Waterfalls", artist: "TLC", year: 1995, genre: "R&B", mood: ["cautionary", "lush"], tier: "hit", why: "AIDS, drugs, violence — topics radio didn't touch in 1995. TLC made them into the biggest song of the year." },
      { rank: 3, title: "...Baby One More Time", artist: "Britney Spears", year: 1998, genre: "Pop", mood: ["teen pop peak", "era-defining"], tier: "hit", why: "Britney was 16. The schoolgirl outfit was her idea. Max Martin's production is clinical perfection. TRL went nuclear." },
      { rank: 4, title: "Gangsta's Paradise", artist: "Coolio ft. L.V.", year: 1995, genre: "Hip-Hop", mood: ["cinematic", "heavy"], tier: "hit", why: "Samples Stevie Wonder's Pastime Paradise. Coolio was furious Weird Al parodied it. It was the best-selling single of 1995." },
      { rank: 5, title: "Killing Me Softly", artist: "Fugees", year: 1996, genre: "Hip-Hop/Soul", mood: ["warm", "effortless"], tier: "hit", why: "Lauryn Hill's voice. Wyclef's guitar. A 1973 Roberta Flack song transformed into something completely new. 18 million copies." },
      { rank: 6, title: "No Scrubs", artist: "TLC", year: 1999, genre: "R&B", mood: ["sharp", "unapologetic"], tier: "hit", why: "Women telling men exactly what they think on mainstream radio. It sounds obvious now. In 1999 it was a statement." },
      { rank: 7, title: "Wonderwall", artist: "Oasis", year: 1995, genre: "Britpop", mood: ["romantic", "massive"], tier: "hit", why: "Liam Gallagher says he hates it. Noel Gallagher wrote it on acoustic in a hotel room. Every open mic in the world still plays it." },
      { rank: 8, title: "One Sweet Day", artist: "Mariah Carey & Boyz II Men", year: 1995, genre: "R&B/Pop", mood: ["grief", "soaring"], tier: "hit", why: "Sixteen weeks at #1. The record stood for 23 years. Written after both acts lost people they loved. The grief is real." },
      { rank: 9, title: "Losing My Religion", artist: "R.E.M.", year: 1991, genre: "Alternative", mood: ["anxious", "confessional"], tier: "hit", why: "Mandolin on MTV. Michael Stipe says it's about unrequited love. America assumed it was about faith. Both readings work." },
      { rank: 10, title: "California Love", artist: "2Pac ft. Dr. Dre", year: 1995, genre: "Hip-Hop", mood: ["West Coast anthem", "celebratory"], tier: "hit", why: "2Pac just got out of prison. Dr. Dre just left Death Row. Roger Troutman's talkbox. The most triumphant moment in West Coast hip-hop." },
      { rank: 11, title: "Say My Name", artist: "Destiny's Child", year: 1999, genre: "R&B", mood: ["suspicious", "flawless"], tier: "defining", why: "Rodney Jerkins production. Beyoncé suspicious, Kelly and Michelle harmonising. The late 90s R&B template, perfected." },
      { rank: 12, title: "Unfinished Sympathy", artist: "Massive Attack", year: 1991, genre: "Trip-Hop", mood: ["cinematic", "weightless"], tier: "defining", why: "A 40-piece orchestra recorded in LA. Shara Nelson's vocal. Bristol's finest export. The song that invented trip-hop." },
      { rank: 13, title: "Common People", artist: "Pulp", year: 1995, genre: "Britpop", mood: ["class warfare", "anthemic"], tier: "defining", why: "Jarvis Cocker at the Brits, dancing behind Michael Jackson. This song is why. Class rage disguised as a piano pop anthem." },
      { rank: 14, title: "Doo Wop (That Thing)", artist: "Lauryn Hill", year: 1998, genre: "Neo-Soul", mood: ["sharp", "beautiful"], tier: "defining", why: "Debut solo single. #1 in its first week. She split the video: 1967 on one side, 1998 on the other. The message unchanged." },
      { rank: 15, title: "The Rain (Supa Dupa Fly)", artist: "Missy Elliott", year: 1997, genre: "Hip-Hop", mood: ["futuristic", "confident"], tier: "defining", why: "Timbaland production. The inflatable suit. Missy rapping from angles nobody had tried. The future, announced." },
      { rank: 16, title: "Brown Sugar", artist: "D'Angelo", year: 1995, genre: "Neo-Soul", mood: ["warm", "sensual"], tier: "defining", why: "The neo-soul movement has an exact birthday. January 10, 1995. When Brown Sugar was released." },
      { rank: 17, title: "Da Funk", artist: "Daft Punk", year: 1995, genre: "Electronic", mood: ["raw", "underground"], tier: "defining", why: "Two Frenchmen in robot helmets. A distorted bass. The first signal that something seismic was coming from Paris." },
      { rank: 18, title: "Zombie", artist: "The Cranberries", year: 1994, genre: "Alternative Rock", mood: ["protest", "raw emotion"], tier: "defining", why: "Written after the 1993 Warrington bombings. Dolores O'Riordan is furious and grieving and the recording captures both." },
      { rank: 19, title: "Enter Sandman", artist: "Metallica", year: 1991, genre: "Metal", mood: ["dark", "stadium-sized"], tier: "defining", why: "Their most accessible song. The Black Album goes 17x platinum. Metal's commercial peak and artistic legitimacy, simultaneously." },
      { rank: 20, title: "Nuthin' But a G Thang", artist: "Dr. Dre ft. Snoop Dogg", year: 1992, genre: "Hip-Hop", mood: ["West Coast", "effortless cool"], tier: "defining", why: "The G-funk blueprint. Leon Haywood sample. Snoop's first major record. The Chronic changes hip-hop production forever." },
      { rank: 21, title: "Black Hole Sun", artist: "Soundgarden", year: 1994, genre: "Grunge", mood: ["surreal", "dark beauty"], tier: "deepcut", why: "The most surreal hit of the decade. That chord sequence. The melting faces in the video. Chris Cornell doing something nobody else could." },
      { rank: 22, title: "Creep", artist: "Radiohead", year: 1992, genre: "Alternative", mood: ["self-loathing", "universal"], tier: "deepcut", why: "Radiohead hated it. Called it their worst song. Played it reluctantly for years. Three billion streams says the audience disagreed." },
      { rank: 23, title: "Protection", artist: "Massive Attack ft. Tracey Thorn", year: 1994, genre: "Trip-Hop", mood: ["late night", "intimate"], tier: "deepcut", why: "Everything But The Girl's Tracey Thorn. The most tender thing in trip-hop's catalogue. Headphones, midnight, essential." },
      { rank: 24, title: "Ex-Factor", artist: "Lauryn Hill", year: 1998, genre: "Neo-Soul", mood: ["heartbreak", "masterclass"], tier: "deepcut", why: "The Miseducation's emotional centrepiece. Samples Wu-Tang. Lauryn's voice breaking in exactly the right places." },
      { rank: 25, title: "Fake Plastic Trees", artist: "Radiohead", year: 1995, genre: "Alternative", mood: ["quiet devastation", "building"], tier: "deepcut", why: "Thom Yorke cried recording it. Producer John Leckie says the control room went silent. They kept the first take." },
      { rank: 26, title: "Tangerine", artist: "Led Zeppelin", year: 1970, genre: "Folk Rock", mood: ["gentle", "overlooked"], tier: "deepcut", why: "From the same album as Immigrant Song. Acoustic, intimate. Shows the range they never got credit for." },
      { rank: 27, title: "Tonight Tonight", artist: "The Smashing Pumpkins", year: 1995, genre: "Alternative Rock", mood: ["orchestral", "cinematic"], tier: "deepcut", why: "The Méliès-inspired video. Full orchestra. Billy Corgan at his most ambitious. The 90s alt-rock peak that gets underplayed." },
      { rank: 28, title: "Firestarter", artist: "The Prodigy", year: 1996, genre: "Electronic/Big Beat", mood: ["aggressive", "explosive"], tier: "deepcut", why: "A punk riff, a breakbeat, and Keith Flint's face on Top of the Pops. Parents were concerned. That was the point." },
      { rank: 29, title: "Bitter Sweet Symphony", artist: "The Verve", year: 1997, genre: "Britpop", mood: ["epic", "bittersweet"], tier: "deepcut", why: "Samples a Rolling Stones orchestral version. The Stones took all royalties. Richard Ashcroft spent 23 years fighting to get his name back on it." },
      { rank: 30, title: "Stan", artist: "Eminem ft. Dido", year: 2000, genre: "Hip-Hop", mood: ["obsessive", "chilling"], tier: "deepcut", why: "Technically 2000 but it's the decade's conclusion. The word \"stan\" is now in the dictionary. Eminem turns fan obsession into tragedy." },
    ],
    bridges: [
      { then: "Nirvana", now: "Wet Leg", why: "Guitar energy, couldn't-care-less cool, discomfort with fame" },
      { then: "Lauryn Hill", now: "SZA", why: "Neo-soul mastery, emotional honesty, complete artistic vision" },
      { then: "TLC", now: "Chlöe", why: "R&B with personality, edge, and something actually to say" },
      { then: "Oasis", now: "Arctic Monkeys", why: "British rock swagger, quotable lyrics, mythology over music press" },
      { then: "Missy Elliott", now: "Doja Cat", why: "Genre-bending hip-hop, visual creativity, one step ahead" },
      { then: "Radiohead", now: "Bon Iver", why: "Emotional weight, sonic experimentation, refuses easy listening" },
      { then: "Massive Attack", now: "James Blake", why: "Trip-hop DNA, bass and soul, melancholy as a production value" },
      { then: "D'Angelo", now: "Frank Ocean", why: "Neo-soul, vulnerability as strength, on their own schedule" },
      { then: "Daft Punk", now: "Fred again..", why: "Electronic music as emotional experience, not just dancefloor" },
      { then: "Destiny's Child", now: "Beyoncé", why: "Obviously, but the lineage is worth naming explicitly" },
    ],
  },

  "2000s": {
    decade: "2000s",
    years: "2000–2009",
    tagline: "Pop at its most glossy. Hip-hop at its most dominant. The iPod in every pocket.",
    theme: {
      bg: "#000a08",
      bgCard: "#001510",
      accent: "#00FF88",
      accentDim: "rgba(0,255,136,0.1)",
      accentBorder: "rgba(0,255,136,0.25)",
      text: "#D0FFE8",
      textMuted: "#40806A",
      gradient: "linear-gradient(135deg, #000a08 0%, #001a10 50%, #000a08 100%)",
      heroGradient: "linear-gradient(180deg, #003020 0%, #000a08 100%)",
      pill: "#001a10",
      font: "'Trebuchet MS', sans-serif",
    },
    era: {
      headline: "Welcome to the 2000s",
      subline: "The iPod has 1,000 songs in your pocket. TRL is on. MySpace is your identity.",
      description: "Beyoncé just went solo. Kanye is rewriting hip-hop. Emo kids are taking over Hot Topic. And in a garage in Cupertino, someone is quietly planning to destroy the music industry.",
    },
    genres: ["Pop (radio maximalism)", "Hip-Hop", "R&B", "Emo / Pop Punk", "Indie Rock", "Electronic/Dance", "Country Pop", "Singer-Songwriter"],
    culturalMoments: [
      {
        title: "The iPod arrives — October 2001",
        body: "\"1,000 songs in your pocket.\" You could carry your entire music collection everywhere. The CD store starts its slow death. Music becomes weightless for the first time.",
      },
      {
        title: "MySpace was the first music social network",
        body: "Every band had a profile. You judged people by their Top 8 and their profile song. Discovery happened between friends, not algorithms. The profile song was a statement of identity.",
      },
      {
        title: "iTunes and the 99-cent single",
        body: "The album as a format starts crumbling. Why buy 12 songs when you want one? The industry fights it. The listeners win. Albums will never fully recover.",
      },
      {
        title: "Hip-hop is the mainstream",
        body: "Not a subculture anymore. Kanye West, Jay-Z, Eminem and Beyoncé are the biggest artists on the planet. The Grammy for Album of the Year starts going to rap records.",
      },
    ],
    definingAlbum: {
      title: "The College Dropout",
      artist: "Kanye West",
      year: 2004,
      why: "He wasn't supposed to rap. Def Jam passed. He made it anyway. Chipmunk soul samples, confessional lyrics, skits about consumerism — it changed what hip-hop could say.",
    },
    songs: [
      { rank: 1, title: "Crazy in Love", artist: "Beyoncé ft. Jay-Z", year: 2003, genre: "R&B/Pop", mood: ["unstoppable", "iconic entrance"], tier: "hit", why: "The horn stab. The hair flip. The solo album begins. Everything about this was a declaration: Beyoncé has arrived." },
      { rank: 2, title: "Yeah!", artist: "Usher ft. Lil Jon & Ludacris", year: 2004, genre: "Hip-Hop/R&B", mood: ["club peak", "era-defining"], tier: "hit", why: "Lil Jon's crunk production, Usher's falsetto, Ludacris's verse. Twelve weeks at #1. Every club from 2004-2007." },
      { rank: 3, title: "In Da Club", artist: "50 Cent", year: 2003, genre: "Hip-Hop", mood: ["swagger", "Dr. Dre production"], tier: "hit", why: "Dr. Dre made the beat in seven minutes. 50 wrote to it that night. The most dominant debut of the decade." },
      { rank: 4, title: "Lose Yourself", artist: "Eminem", year: 2002, genre: "Hip-Hop", mood: ["desperate ambition", "cinematic"], tier: "hit", why: "Written in his car between takes on 8 Mile. The only rap song to win the Academy Award for Best Original Song." },
      { rank: 5, title: "Since U Been Gone", artist: "Kelly Clarkson", year: 2004, genre: "Pop/Rock", mood: ["cathartic", "fist-pump chorus"], tier: "hit", why: "Max Martin and Lukasz Gottwald wrote it. The guitar crunch shouldn't work on an Idol winner. It completely works." },
      { rank: 6, title: "Hey Ya!", artist: "OutKast", year: 2003, genre: "Pop/Hip-Hop", mood: ["joyful", "deeper than it sounds"], tier: "hit", why: "André 3000 played every instrument. The lyrics are about a relationship falling apart. It sounds like the best party ever." },
      { rank: 7, title: "Umbrella", artist: "Rihanna", year: 2007, genre: "Pop/R&B", mood: ["sleek", "bulletproof pop"], tier: "hit", why: "Written for Britney, Mary J. Blige, and Ciara first. All passed. Rihanna made it iconic. The 'ella ella ella' is still everywhere." },
      { rank: 8, title: "Mr. Brightside", artist: "The Killers", year: 2003, genre: "Indie Rock", mood: ["jealousy", "endless energy"], tier: "hit", why: "Brandon Flowers wrote it about watching his girlfriend leave with someone else. Never left the UK charts. Not once." },
      { rank: 9, title: "Toxic", artist: "Britney Spears", year: 2003, genre: "Pop", mood: ["sleek", "perfect"], tier: "hit", why: "Bollywood strings, spy film production, Britney at her most creative. Critics have spent twenty years catching up to it." },
      { rank: 10, title: "Gold Digger", artist: "Kanye West ft. Jamie Foxx", year: 2005, genre: "Hip-Hop", mood: ["sharp", "sample mastery"], tier: "hit", why: "Ray Charles, a chipmunk sample, and Kanye at his most playful. His first #1. Produced in under an hour, allegedly." },
      { rank: 11, title: "Crazy", artist: "Gnarls Barkley", year: 2006, genre: "Soul/Pop", mood: ["timeless", "genre-fluid"], tier: "defining", why: "Cee Lo Green and Danger Mouse. Samples Gian Franco Reverberi. First song ever to chart based on downloads alone." },
      { rank: 12, title: "Welcome to the Black Parade", artist: "My Chemical Romance", year: 2006, genre: "Emo/Rock", mood: ["theatrical", "cathartic"], tier: "defining", why: "A rock opera in four minutes. A marching band, a cancer patient, a Gerard Way monologue. Emo's loudest moment." },
      { rank: 13, title: "Seven Nation Army", artist: "The White Stripes", year: 2003, genre: "Rock", mood: ["stripped back", "unforgettable riff"], tier: "defining", why: "Jack White plays it on guitar through an octave pedal. No bass player. That riff is now a global football chant." },
      { rank: 14, title: "Paper Planes", artist: "M.I.A.", year: 2007, genre: "Electronic/Hip-Hop", mood: ["provocative", "global"], tier: "defining", why: "Gunshots and cash registers as percussion. Diplo production. Slumdog Millionaire, Pineapple Express, Trainspotting 2 — everyone wanted it." },
      { rank: 15, title: "Single Ladies", artist: "Beyoncé", year: 2008, genre: "Pop/R&B", mood: ["commanding", "cultural moment"], tier: "defining", why: "Shot in one take in three hours. Kanye interrupted Taylor Swift for it. The choreography has been copied ten thousand times." },
      { rank: 16, title: "Jesus Walks", artist: "Kanye West", year: 2004, genre: "Hip-Hop", mood: ["ambitious", "spiritual"], tier: "defining", why: "Three labels turned it down. Kanye released it anyway. A rap song about God on pop radio. It changed what hip-hop could risk." },
      { rank: 17, title: "Float On", artist: "Modest Mouse", year: 2004, genre: "Indie Rock", mood: ["optimistic", "indie breakthrough"], tier: "defining", why: "Isaac Brock's catchiest chord progression. Indie music's moment of genuine mainstream crossover." },
      { rank: 18, title: "Rebellion (Lies)", artist: "Arcade Fire", year: 2004, genre: "Indie Rock", mood: ["anthemic", "generational"], tier: "defining", why: "Win Butler, Régine Chassagne, and nine other people making music that sounded like a revolution. It was." },
      { rank: 19, title: "The District Sleeps Alone Tonight", artist: "The Postal Service", year: 2003, genre: "Indie Electronic", mood: ["melancholy", "beautiful"], tier: "defining", why: "Ben Gibbard and Jimmy Tamborello mailed each other files. Death Cab meets electronic. The bedroom pop origin story." },
      { rank: 20, title: "Harder Better Faster Stronger", artist: "Daft Punk", year: 2001, genre: "Electronic", mood: ["robotic euphoria", "meticulous"], tier: "defining", why: "Samples Edwin Birdsong's Cola Bottle Baby. Thomas Bangalter and Guy-Manuel in helmets, changing the dancefloor forever." },
      { rank: 21, title: "Take Me Out", artist: "Franz Ferdinand", year: 2004, genre: "Indie Rock", mood: ["angular", "danceable"], tier: "deepcut", why: "The rhythm change at 40 seconds. Every indie disco 2004-2008 played this. Glasgow art school rock at its finest." },
      { rank: 22, title: "B.O.B.", artist: "OutKast", year: 2000, genre: "Hip-Hop", mood: ["relentless", "technically stunning"], tier: "deepcut", why: "180 BPM. André 3000 and Big Boi trading verses at breakneck pace. Hayley Williams on the outro. Two years ahead of its time." },
      { rank: 23, title: "First Day of My Life", artist: "Bright Eyes", year: 2005, genre: "Indie Folk", mood: ["romantic", "quietly devastating"], tier: "deepcut", why: "Conor Oberst at his most simply beautiful. An alternative wedding song for people who knew the other ones were pretending." },
      { rank: 24, title: "Mushaboom", artist: "Feist", year: 2004, genre: "Indie Folk", mood: ["warm", "intimate"], tier: "deepcut", why: "A fantasy about a farmhouse and a family. The Apple iPod ad made it famous. The song deserved better than that association." },
      { rank: 25, title: "NYC", artist: "Interpol", year: 2002, genre: "Post-Punk Revival", mood: ["dark", "atmospheric"], tier: "deepcut", why: "Post 9/11 New York, through the lens of Joy Division fans in black turtlenecks. Somehow exactly right for the moment." },
      { rank: 26, title: "Breathe (2 AM)", artist: "Anna Nalick", year: 2005, genre: "Singer-Songwriter", mood: ["2am emotional wreck", "honest"], tier: "deepcut", why: "\"Just breathe\" — the best advice in any song of the decade. Underheard, underrated, still gets people through hard nights." },
      { rank: 27, title: "Lights and Music", artist: "Cut Copy", year: 2008, genre: "Electronic", mood: ["euphoric", "overlooked"], tier: "deepcut", why: "Melbourne's finest export. Indie dance at its peak. Every person who heard it at a festival became a missionary for it." },
      { rank: 28, title: "Chelsea Dagger", artist: "The Fratellis", year: 2006, genre: "Indie Rock", mood: ["euphoric", "raucous"], tier: "deepcut", why: "A pub rock song that became a stadium anthem. Every hockey team uses it. Jon Fratelli wrote it about a burlesque dancer." },
      { rank: 29, title: "Hollaback Girl", artist: "Gwen Stefani", year: 2005, genre: "Pop", mood: ["absurd", "unforgettable"], tier: "deepcut", why: "Pharrell produced it in response to Courtney Love calling Gwen a cheerleader. \"This my shit\" is iconic for reasons nobody can explain." },
      { rank: 30, title: "Neighbourhood #1 (Tunnels)", artist: "Arcade Fire", year: 2004, genre: "Indie Rock", mood: ["wintry", "magical"], tier: "deepcut", why: "The Funeral opener. Snow, childhood, loss — Win Butler building a mythology from Montreal suburban grief." },
    ],
    bridges: [
      { then: "Beyoncé (2003)", now: "Beyoncé (2023)", why: "She just kept going and somehow kept getting better" },
      { then: "Kanye West", now: "Tyler the Creator", why: "Genre-breaking hip-hop auteur, production as artistic vision" },
      { then: "The Killers", now: "Bleachers", why: "Anthemic indie rock, big feelings, American mythology" },
      { then: "My Chemical Romance", now: "Olivia Rodrigo", why: "Emotional catharsis, teen angst given full artistic legitimacy" },
      { then: "Arcade Fire", now: "The National", why: "Indie rock with literary ambition, orchestral arrangements" },
      { then: "OutKast", now: "Childish Gambino", why: "Genre-fluid hip-hop, artistic restlessness, refuses the obvious" },
      { then: "M.I.A.", now: "Charli XCX", why: "Global pop that refuses neat categories, always provocateur" },
      { then: "Feist", now: "Phoebe Bridgers", why: "Intimate indie folk, emotionally precise, voice as instrument" },
      { then: "Daft Punk", now: "Justice", why: "French electronic lineage, maximalist production, helmets optional" },
      { then: "Kelly Clarkson", now: "Paramore", why: "Pop-rock with genuine teeth, the chorus earns every note" },
    ],
  },

  "2010s": {
    decade: "2010s",
    years: "2010–2019",
    tagline: "Streaming killed the album. The internet made everything niche. And somehow everyone knew the same songs anyway.",
    theme: {
      bg: "#080010",
      bgCard: "#0f001a",
      accent: "#6C63FF",
      accentDim: "rgba(108,99,255,0.12)",
      accentBorder: "rgba(108,99,255,0.3)",
      text: "#E8E0FF",
      textMuted: "#6050A0",
      gradient: "linear-gradient(135deg, #080010 0%, #100020 50%, #080010 100%)",
      heroGradient: "linear-gradient(180deg, #1a0030 0%, #080010 100%)",
      pill: "#100020",
      font: "'Helvetica Neue', Arial, sans-serif",
    },
    era: {
      headline: "Welcome to the 2010s",
      subline: "Spotify launched. Kendrick dropped. BTS are filling stadiums in Brazil.",
      description: "The album fights for survival. Trap music rewrites hip-hop's DNA. K-pop goes global. Beyoncé drops an album with no warning and changes how music is released forever.",
    },
    genres: ["Pop (maximalist → minimalist)", "Trap / Hip-Hop", "Indie / Alternative", "EDM / Electronic", "New R&B", "K-Pop", "Singer-Songwriter", "Latin Pop"],
    culturalMoments: [
      {
        title: "Spotify launches in the US — 2011",
        body: "Within five years the album is secondary to the playlist. Artists optimize for streams not sales. The skip button is always one thumb away. Music becomes a utility.",
      },
      {
        title: "SoundCloud rap rewrites the rulebook",
        body: "No label, no gatekeepers. Post Malone, XXXTentacion, Lil Pump — recorded in bedrooms, uploaded at midnight, viral by morning. The industry catches up later. Much later.",
      },
      {
        title: "K-Pop goes global",
        body: "BTS sells out stadiums in São Paulo and London. BLACKPINK headlines Coachella. The music industry realizes 'global' no longer means 'American.'",
      },
      {
        title: "The album format fights back",
        body: "Beyoncé drops a visual album with no warning in 2013. Kendrick Lamar releases To Pimp a Butterfly and people write essays about it. Some artists refuse to let streaming win.",
      },
    ],
    definingAlbum: {
      title: "To Pimp a Butterfly",
      artist: "Kendrick Lamar",
      year: 2015,
      why: "Jazz, funk, spoken word, hip-hop — all in service of the most ambitious statement about Black America in a generation. Rolling Stone called it the album of the decade. It probably is.",
    },
    songs: [
      { rank: 1, title: "Rolling in the Deep", artist: "Adele", year: 2010, genre: "Pop/Soul", mood: ["devastating", "unstoppable"], tier: "hit", why: "Recorded after a breakup, in two days. The most-played song of 2011 worldwide. Paul Epworth's production, Adele's fury." },
      { rank: 2, title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", year: 2014, genre: "Funk/Pop", mood: ["pure joy", "throwback done right"], tier: "hit", why: "Fourteen weeks at #1. Credited to 36 songwriters to clear all its samples. Sounds like none of them, sounds like itself." },
      { rank: 3, title: "God's Plan", artist: "Drake", year: 2018, genre: "Hip-Hop", mood: ["generous", "emotional"], tier: "hit", why: "Drake spent the entire video budget giving it away. $996,000 to strangers. The video made everyone feel things about a man in a fur coat." },
      { rank: 4, title: "Old Town Road", artist: "Lil Nas X", year: 2019, genre: "Hip-Hop/Country", mood: ["internet-born", "genre-breaking"], tier: "hit", why: "Made for $30 on a Nine Inch Nails sample. Billboard removed it from country charts. The controversy made it #1 for 19 weeks." },
      { rank: 5, title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", year: 2017, genre: "Latin Pop", mood: ["global crossover", "summer"], tier: "hit", why: "The most-streamed song ever at its release. Latin music's mainstream breakthrough moment. Justin Bieber added a verse. It didn't need him." },
      { rank: 6, title: "Bad Guy", artist: "Billie Eilish", year: 2019, genre: "Alt-Pop", mood: ["subversive", "whispered menace"], tier: "hit", why: "Produced in her brother's bedroom. The bass drop everyone talks about. She was 17, already rewriting what a pop star could be." },
      { rank: 7, title: "Shake It Off", artist: "Taylor Swift", year: 2014, genre: "Pop", mood: ["carefree", "relentless hooks"], tier: "hit", why: "Written in response to years of media criticism. Max Martin and Shellback production. Taylor Swift deciding to be unbothered." },
      { rank: 8, title: "Royals", artist: "Lorde", year: 2013, genre: "Indie Pop", mood: ["anti-pop", "precise"], tier: "hit", why: "She was 16. Written in 30 minutes. The most articulate takedown of pop excess since The Smiths, delivered as a pop song." },
      { rank: 9, title: "HUMBLE.", artist: "Kendrick Lamar", year: 2017, genre: "Hip-Hop", mood: ["commanding", "stripped"], tier: "hit", why: "Mike WiLL Made-It. The hardest Kendrick has ever sounded. One take. The Gregorian chant breakdown. Rap's most dominant moment of the decade." },
      { rank: 10, title: "Hotline Bling", artist: "Drake", year: 2015, genre: "Hip-Hop/R&B", mood: ["melancholy nostalgia", "meme"], tier: "hit", why: "Samples Timmy Thomas's Why Can't We Live Together from 1972. Drake dances. The internet breaks. Both things can be true." },
      { rank: 11, title: "Midnight City", artist: "M83", year: 2011, genre: "Electronic", mood: ["cinematic", "nostalgic future"], tier: "defining", why: "Anthony Gonzalez makes French synth-pop that sounds like the 80s remembered better than the 80s actually were." },
      { rank: 12, title: "Thinking Bout You", artist: "Frank Ocean", year: 2012, genre: "R&B", mood: ["vulnerable", "era-defining"], tier: "defining", why: "Channel Orange's opener. Frank Ocean's formal arrival. R&B decides it no longer needs to explain itself to anyone." },
      { rank: 13, title: "Flawless", artist: "Beyoncé ft. Chimamanda Ngozi Adichie", year: 2013, genre: "Pop/R&B", mood: ["feminist anthem", "commanding"], tier: "defining", why: "A novelist's TED talk on feminism, mid-song. Beyoncé surprises everyone at midnight. A new way to release music, on one night." },
      { rank: 14, title: "DNA.", artist: "Kendrick Lamar", year: 2017, genre: "Hip-Hop", mood: ["intense", "breathtaking"], tier: "defining", why: "Two beats in one song. The second drops at 1:36. Fox News played it to prove rap was dangerous. Kendrick framed the segment." },
      { rank: 15, title: "Redbone", artist: "Childish Gambino", year: 2016, genre: "Funk/Soul", mood: ["psychedelic", "timeless"], tier: "defining", why: "Donald Glover at 3am, three chords, slowed down until it sounds like the 70s reimagined. Get Out used it. Nothing has been the same." },
      { rank: 16, title: "Green Light", artist: "Lorde", year: 2017, genre: "Pop", mood: ["euphoric heartbreak", "piano-driven"], tier: "defining", why: "Jack Antonoff piano. Lorde crying in the verses, screaming in the chorus. Heartbreak sounds like dancing in Lorde's world." },
      { rank: 17, title: "Do I Wanna Know?", artist: "Arctic Monkeys", year: 2013, genre: "Rock", mood: ["slow burning desire", "dark"], tier: "defining", why: "Alex Turner's most literary lyric. That riff. AM is the last great guitar album to go properly mainstream. This is its centrepiece." },
      { rank: 18, title: "Lean On", artist: "Major Lazer ft. MØ", year: 2015, genre: "Electronic/Pop", mood: ["global hit", "effortless"], tier: "defining", why: "Diplo, Jillionaire, and Walshy Fire. MØ's voice. The most-streamed song of 2015. Global pop without a geographic home." },
      { rank: 19, title: "Pink + White", artist: "Frank Ocean", year: 2016, genre: "R&B", mood: ["sun-drenched", "memory"], tier: "defining", why: "Blonde's emotional highlight. Pharrell on the outro. A summer afternoon captured in audio. Beyoncé on backing vocals, uncredited." },
      { rank: 20, title: "Take Care", artist: "Drake ft. Rihanna", year: 2011, genre: "R&B/Hip-Hop", mood: ["nocturnal", "intimate"], tier: "defining", why: "Samples Jamie xx's remix of Gil Scott-Heron. Drake and Rihanna at their most nakedly emotional. The sound of 2am in 2011." },
      { rank: 21, title: "Holocene", artist: "Bon Iver", year: 2011, genre: "Indie Folk", mood: ["vast", "beautiful"], tier: "deepcut", why: "Justin Vernon in a cabin in Wisconsin. Autotune as an instrument not a correction. The most cinematic small song ever written." },
      { rank: 22, title: "Ribs", artist: "Lorde", year: 2013, genre: "Indie Pop", mood: ["teenage existential dread", "exact"], tier: "deepcut", why: "\"You're not my mother and I'm not your son\" — Lorde at 16, naming a feeling most people couldn't articulate at 30." },
      { rank: 23, title: "Youth", artist: "Daughter", year: 2013, genre: "Indie Folk", mood: ["quietly devastating", "winter"], tier: "deepcut", why: "Elena Tonra's voice over a guitar that sounds like it's being played in fog. The most underheard perfect song of the decade." },
      { rank: 24, title: "Bored in the USA", artist: "Father John Misty", year: 2015, genre: "Indie/Folk", mood: ["sardonic", "heartbreaking"], tier: "deepcut", why: "Josh Tillman with canned studio laughter over a litany of modern disappointments. The sharpest lyric of the decade." },
      { rank: 25, title: "PRIDE.", artist: "Kendrick Lamar", year: 2017, genre: "Hip-Hop", mood: ["reflective", "confessional"], tier: "deepcut", why: "The most vulnerable track on DAMN. Kendrick admitting flaws on an album about righteousness. The contrast is the point." },
      { rank: 26, title: "Liability", artist: "Lorde", year: 2017, genre: "Pop", mood: ["raw", "alone at a party"], tier: "deepcut", why: "Just piano and voice. Written about feeling like too much for people. Everyone who has ever felt that has this song in their chest." },
      { rank: 27, title: "Electric Feel", artist: "MGMT", year: 2007, genre: "Indie/Electronic", mood: ["euphoric", "hazy"], tier: "deepcut", why: "2007 technically but defines 2010-2012 festival culture so completely it belongs here. Every tent stage, every summer." },
      { rank: 28, title: "Motion Sickness", artist: "Phoebe Bridgers", year: 2017, genre: "Indie Folk", mood: ["sharp", "funny and sad"], tier: "deepcut", why: "About a relationship with an older musician who used his influence badly. Phoebe names him on stage three years later." },
      { rank: 29, title: "Oblivion", artist: "Grimes", year: 2012, genre: "Electropop", mood: ["ethereal", "assault disguised as pop"], tier: "deepcut", why: "Claire Boucher wrote it after being assaulted. The most beautiful song about being afraid to go outside." },
      { rank: 30, title: "Crying in the Club", artist: "Camila Cabello", year: 2017, genre: "Pop", mood: ["underrated", "transitional"], tier: "deepcut", why: "Her debut solo single. Forgotten in the rush of Havana. A better pop song than it's given credit for." },
    ],
    bridges: [
      { then: "Adele", now: "Adele", why: "She just keeps doing it, and it keeps working" },
      { then: "Lorde", now: "Billie Eilish", why: "Teenage perspective, the industry on her own terms, quiet fury" },
      { then: "Frank Ocean", now: "Daniel Caesar", why: "R&B vulnerability, artistic control, on their own schedule" },
      { then: "Kendrick Lamar", now: "Kendrick Lamar", why: "Still the standard. No bridge needed. The conversation continues." },
      { then: "Bon Iver", now: "Big Thief", why: "Folk with emotional depth, refuses easy or comfortable listening" },
      { then: "Arctic Monkeys", now: "Inhaler", why: "British rock lineage, Alex Turner's influence everywhere" },
      { then: "Childish Gambino", now: "Steve Lacy", why: "Funk-rooted, genre-refusing, guitar-led Black alternative" },
      { then: "Lil Nas X", now: "Ice Spice", why: "Internet-born, genre-bending, completely and unapologetically themselves" },
      { then: "Major Lazer", now: "Bad Bunny", why: "Global south pop taking over the charts, no permission needed" },
      { then: "M83", now: "Bicep", why: "Electronic music as emotional journey, not just dancefloor function" },
    ],
  },

  "2020s": {
    decade: "2020s",
    years: "2020–present",
    tagline: "Post-pandemic sound. Everything at once. The algorithm vs. the artist.",
    theme: {
      bg: "#030308",
      bgCard: "#08080f",
      accent: "#FF2D78",
      accentDim: "rgba(255,45,120,0.1)",
      accentBorder: "rgba(255,45,120,0.25)",
      text: "#FFE0EC",
      textMuted: "#804060",
      gradient: "linear-gradient(135deg, #030308 0%, #08040f 50%, #030308 100%)",
      heroGradient: "linear-gradient(180deg, #1a001a 0%, #030308 100%)",
      pill: "#0f040f",
      font: "'Inter', system-ui, sans-serif",
    },
    era: {
      headline: "Welcome to the 2020s",
      subline: "A pandemic. A TikTok algorithm. Taylor Swift breaking every record that exists.",
      description: "Afrobeats and Latin music end the American pop monopoly. Bedroom recordings go viral before they're finished. The Eras Tour grosses a billion dollars. And somehow everyone is still arguing about whether streaming is good for music.",
    },
    genres: ["Hyperpop / Alt-Pop", "Afrobeats (global)", "Latin (reggaeton / corridos)", "Bedroom Pop", "Folk / Singer-Songwriter revival", "Trap / Melodic Rap", "Club music revival", "K-Pop"],
    culturalMoments: [
      {
        title: "The pandemic silences live music for two years",
        body: "Artists make albums in isolation. Bedroom pop becomes an aesthetic, not just a genre. Heat Waves by Glass Animals sits on the charts for 90 weeks. The song about missing someone resonates globally.",
      },
      {
        title: "TikTok becomes the most powerful discovery platform on earth",
        body: "A 15-second clip can turn a 2014 song into a 2021 hit. Algorithms choose what goes viral. Artists start writing songs for the first 15 seconds. Some resist. Most don't.",
      },
      {
        title: "Afrobeats and Latin music take over the global charts",
        body: "Bad Bunny is the most-streamed artist on Spotify three years running. Burna Boy and Wizkid fill arenas in London. Tyla wins a Grammy for a genre category created specifically for her. The American pop monopoly is over.",
      },
      {
        title: "Taylor Swift breaks every record that exists",
        body: "The Eras Tour becomes the first concert tour to gross over a billion dollars. She single-handedly moves the economy of every city she visits. Somehow she also releases four albums in the same period.",
      },
    ],
    definingAlbum: {
      title: "Sour",
      artist: "Olivia Rodrigo",
      year: 2021,
      why: "Recorded during lockdown at 17. Debut album. Broke Spotify's first-day streaming record. Seven Grammy nominations. Pop punk, ballads, angry breakup rock — all of it completely genuine.",
    },
    songs: [
      { rank: 1, title: "drivers license", artist: "Olivia Rodrigo", year: 2021, genre: "Pop", mood: ["teenage heartbreak", "record-breaking"], tier: "hit", why: "Zero to 76 million Spotify streams in a week. Written at 17 about a driver's test and a boy. Specific enough to feel universal." },
      { rank: 2, title: "Levitating", artist: "Dua Lipa", year: 2020, genre: "Pop/Disco", mood: ["euphoric", "future disco"], tier: "hit", why: "Future Nostalgia's centrepiece. Disco for people who were born after disco died. The album that made pop cool in a pandemic year." },
      { rank: 3, title: "As It Was", artist: "Harry Styles", year: 2022, genre: "Pop", mood: ["melancholy bop", "inescapable"], tier: "hit", why: "Fifteen weeks at #1. Kid Harpoon and Tyler Johnson production. The most listened-to song on Spotify in 2022 by a significant margin." },
      { rank: 4, title: "MONTERO (Call Me By Your Name)", artist: "Lil Nas X", year: 2021, genre: "Pop/Hip-Hop", mood: ["provocative", "historic"], tier: "hit", why: "The pole dance to hell. The Satan shoes. The Governor of Montana complained. Lil Nas X responded with a press release mocking him." },
      { rank: 5, title: "Heat Waves", artist: "Glass Animals", year: 2020, genre: "Indie Pop", mood: ["lockdown longing", "slow-burn viral"], tier: "hit", why: "91 weeks on the Billboard Hot 100. A record. About missing a dead friend. TikTok found it two years after release and never let go." },
      { rank: 6, title: "Flowers", artist: "Miley Cyrus", year: 2023, genre: "Pop", mood: ["self-love anthem", "perfect comeback"], tier: "hit", why: "Released on Liam Hemsworth's birthday. About buying herself flowers. The references are surgical. The production is spotless." },
      { rank: 7, title: "Anti-Hero", artist: "Taylor Swift", year: 2022, genre: "Pop", mood: ["self-aware", "massive"], tier: "hit", why: "\"It's me, hi, I'm the problem, it's me.\" Eight weeks at #1. Jack Antonoff production. The most self-aware megahit in years." },
      { rank: 8, title: "Cruel Summer", artist: "Taylor Swift", year: 2019, genre: "Pop", mood: ["euphoric anxiety", "delayed triumph"], tier: "hit", why: "Released in 2019, viral in 2023 after the Eras Tour. Took four years for the world to catch up to how good it was." },
      { rank: 9, title: "Essence", artist: "Wizkid ft. Tems", year: 2020, genre: "Afrobeats", mood: ["warm", "irresistible"], tier: "hit", why: "Tems's voice on this song changed her life and Afrobeats' global reach simultaneously. Justin Bieber added a remix. He was right to want in." },
      { rank: 10, title: "Easy On Me", artist: "Adele", year: 2021, genre: "Pop/Soul", mood: ["quiet devastation", "return"], tier: "hit", why: "Nineteen weeks at #1 in the UK. The piano. The breath. Adele explaining a divorce to her son. Nobody else could make this song." },
      { rank: 11, title: "good 4 u", artist: "Olivia Rodrigo", year: 2021, genre: "Pop Punk", mood: ["cathartic rage", "Paramore DNA"], tier: "defining", why: "Hayley Williams got a co-writing credit. The guitar is borrowed from Misery Business. The fury is entirely Olivia's own." },
      { rank: 12, title: "Happier Than Ever", artist: "Billie Eilish", year: 2021, genre: "Pop", mood: ["quiet fury building", "two-part"], tier: "defining", why: "Bossa nova for three minutes then distorted guitars for two. The transition is the whole point. Anger arriving late." },
      { rank: 13, title: "Escapism.", artist: "RAYE ft. 070 Shake", year: 2022, genre: "R&B/Pop", mood: ["raw", "4am falling apart"], tier: "defining", why: "RAYE wrote it after being dropped by her label. Took six years. It went #1 the week it was released. The industry owed her." },
      { rank: 14, title: "Vampire", artist: "Olivia Rodrigo", year: 2023, genre: "Pop Rock", mood: ["precise anger", "cinematic"], tier: "defining", why: "The piano ballad that becomes a rock song. \"Bloodsucker, famef*cker\" — the most specifically aimed lyric of the decade so far." },
      { rank: 15, title: "Water", artist: "Tyla", year: 2023, genre: "Afrobeats/Pop", mood: ["effortless", "Grammy-making"], tier: "defining", why: "She was 21. Grammy for Best African Music Performance. A new category created, in part, because of her. South Africa arrives." },
      { rank: 16, title: "Ella Baila Sola", artist: "Eslabon Armado & Peso Pluma", year: 2023, genre: "Regional Mexican", mood: ["genre crossover", "historic"], tier: "defining", why: "The most-streamed Spanish-language song ever at release. Regional Mexican music on a global scale. The charts rewritten again." },
      { rank: 17, title: "Bzrp Music Sessions #53", artist: "Bizarrap & Shakira", year: 2023, genre: "Latin/Pop", mood: ["revenge served cold", "precise"], tier: "defining", why: "274 million YouTube views in a week. Shakira names her ex-husband's new girlfriend's brands. Piqué sells the Renault. The internet goes feral." },
      { rank: 18, title: "Industry Baby", artist: "Lil Nas X ft. Jack Harlow", year: 2021, genre: "Hip-Hop/Pop", mood: ["triumphant", "bold"], tier: "defining", why: "Shot in a prison. On trial for being gay. Lil Nas X making every response into a cultural event. His artistry is the argument." },
      { rank: 19, title: "Telepatía", artist: "Kali Uchis", year: 2020, genre: "Latin R&B", mood: ["dreamy", "bilingual cool"], tier: "defining", why: "Colombian-American Kali Uchis goes fully Spanish. The sound is warm and weightless. The crossover nobody was pushing for happens anyway." },
      { rank: 20, title: "Running Up That Hill", artist: "Kate Bush", year: 1985, genre: "Art Pop", mood: ["timeless", "Stranger Things resurrected"], tier: "defining", why: "Yes, a 1985 song. But Stranger Things Season 4 put it at #1 in 2022, 37 years after release. The 2020s absorbed it. Kate Bush deserved it." },
      { rank: 21, title: "Savior Complex", artist: "Phoebe Bridgers", year: 2020, genre: "Indie Folk", mood: ["devastating", "quiet"], tier: "deepcut", why: "The most painful song on Punisher. About knowing a relationship is wrong and staying anyway. The horns at the end are a gut punch." },
      { rank: 22, title: "Collapsed in Sunbeams", artist: "Arlo Parks", year: 2021, genre: "Indie/R&B", mood: ["warm", "observational"], tier: "deepcut", why: "Anaïs Mitchell meets Frank Ocean in a London bedroom. Arlo Parks writing about her friends with the tenderness of someone who pays attention." },
      { rank: 23, title: "Glimpse of Us", artist: "Joji", year: 2022, genre: "R&B/Pop", mood: ["bittersweet", "internet-native"], tier: "deepcut", why: "George Miller, who was Filthy Frank on YouTube, makes the most tender heartbreak song of the year. The career arc is extraordinary." },
      { rank: 24, title: "fukumean", artist: "Gunna", year: 2023, genre: "Trap", mood: ["slang as art", "Atlanta peak"], tier: "deepcut", why: "Recorded after a prison sentence. The ad-libs are the lyrics. Atlanta trap at its most self-assured. You either feel it or you don't." },
      { rank: 25, title: "King of Anything", artist: "Fred again.. ft. Obongjayar", year: 2022, genre: "Electronic", mood: ["emotional", "rave-adjacent"], tier: "deepcut", why: "Fred Gibson samples a voice note from a friend. Obongjayar turns it into something spiritual. Brian Eno mentored him. It shows." },
      { rank: 26, title: "Victoria's Secret", artist: "Jax", year: 2022, genre: "Pop", mood: ["body image anthem", "TikTok-born"], tier: "deepcut", why: "Written about her own eating disorder. Went viral before she had a label. A pop song doing what pop songs used to do — naming something real." },
      { rank: 27, title: "All I Want", artist: "Kodaline", year: 2012, genre: "Indie", mood: ["aching", "TikTok rediscovered"], tier: "deepcut", why: "A 2012 song that lives in 2020s TikTok grief compilations. The decade of algorithmic rediscovery claims another victim." },
      { rank: 28, title: "Hardstone Psycho", artist: "Don Toliver", year: 2024, genre: "Hip-Hop/R&B", mood: ["psychedelic", "nocturnal"], tier: "deepcut", why: "Travis Scott's prodigy making a whole album that sounds like being inside a moving car at 2am with no destination." },
      { rank: 29, title: "Midnight Rain", artist: "Taylor Swift", year: 2022, genre: "Pop", mood: ["dual narrative", "layered"], tier: "deepcut", why: "Two voices, two lives, one decision. Taylor's voice slowed to a baritone over her own falsetto. Midnights' secret best track." },
      { rank: 30, title: "Motion Sickness (live at Red Rocks)", artist: "Phoebe Bridgers", year: 2021, genre: "Indie Folk", mood: ["cathartic", "communal"], tier: "deepcut", why: "The studio version is sharp. The live version with 9,000 people singing every word is when it becomes something else entirely." },
    ],
    bridges: [
      { then: "Olivia Rodrigo", now: "Gracie Abrams", why: "Quiet vulnerability, precise hurt, industry insider with outsider soul" },
      { then: "Billie Eilish", now: "Sabrina Carpenter", why: "Pop on her own terms, wit underneath the surface, always a step ahead" },
      { then: "Wizkid & Tems", now: "Tyla", why: "Afrobeats next generation, already Grammy-winning, just getting started" },
      { then: "Bad Bunny", now: "Peso Pluma", why: "Latin music keeps fragmenting and conquering, the genre has no ceiling" },
      { then: "Fred again..", now: "Four Tet", why: "The continuum of British electronic emotion, feelings as production" },
      { then: "Phoebe Bridgers", now: "Julien Baker", why: "Folk rock that doesn't let you off easy, sadness as precision instrument" },
      { then: "Lil Nas X", now: "Ice Spice", why: "Internet-born, genre-refusing, completely and defiantly themselves" },
      { then: "Glass Animals", now: "Wet Leg", why: "British indie that found its moment through persistence, not hype" },
      { then: "Arlo Parks", now: "Samia", why: "Intimate indie observation, emotional precision, small details made large" },
      { then: "The Weeknd", now: "Don Toliver", why: "Nocturnal R&B, cinematic darkness, Houston to Toronto lineage" },
    ],
  },
};

export type DecadeKey = keyof typeof DECADES;

export const DECADE_ORDER: DecadeKey[] = [
  "1970s",
  "1980s",
  "1990s",
  "2000s",
  "2010s",
  "2020s",
];

export function getDecade(decade: DecadeKey) {
  return DECADES[decade];
}

export function getBirthDecade(year: number): DecadeKey {
  if (year < 1975) return "1970s";
  if (year < 1985) return "1980s";
  if (year < 1995) return "1990s";
  if (year < 2005) return "2000s";
  if (year < 2015) return "2010s";
  return "2020s";
}

export function getHighSchoolDecade(year: number): DecadeKey {
  const hsYear = year + 15;
  return getBirthDecade(hsYear - 10);
}